#! /usr/bin/python

import re
import sys
import tweets

if len(sys.argv) < 3:
  sys.stderr.write("USAGE: %s /path/to/tweets.zip <python-regexp> [ADILMSX]\n" % __file__)
  exit(1)

__, filename, rx, *__ = sys.argv

flags = 0
if len(sys.argv) > 3:
  for c in sys.argv[3]:
    if c.upper() not in re.__dict__ or not isinstance(re.__dict__[c.upper()], int):
      sys.stderr.write("ERROR: Unknown flag `%s'\n" % c)
      exit(1)
    flags |= re.__dict__[c.upper()]

pat = re.compile(rx, flags = flags)

def __hljudge():
  try:
    import __main__
    __main__.termcolor = __import__("termcolor")
    return sys.stdout.isatty()
  except ImportError:
    return False

hlflag = __hljudge()

for tw in tweets.open(filename):
  if "retweeted_status" in tw:
    text = "RT @%s: %s" % (tw["retweeted_status"]["user"]["screen_name"], tw["retweeted_status"]["text"])
  else:
    text = tw["text"]
  if pat.search(text):
    if hlflag:
      text = pat.sub(lambda m: termcolor.colored(m.group(0), "red"), text)
    print("%s [%s]" % (
      text,
      "https://twitter.com/%s/statuses/%d/" % (tw["user"]["screen_name"], tw["id"])
    ))
