#! /usr/bin/python3

import tweetsziptools as tweets
import sys

# dependency
from matplotlib import pyplot

if len(sys.argv) < 2:
  sys.stderr.write("USAGE: %s /path/to/tweets.zip\n" % __file__)
  exit(1)

HOURS = range(0, 24)
counter = [0 for i in HOURS]
for tw in tweets.open(sys.argv[1]):
  d = tweets.parse_created_at(tw["created_at"])
  counter[d.hour] += 1

for h, val in enumerate(counter):
  print("%02d: %d" % (h, val))

pyplot.figure("hourly")
pyplot.bar(*list(zip(*enumerate(counter))))
pyplot.show()
